development:
  adapter: mysql2
  encoding: utf8
  database: LifeBoySchool_development
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  database: LifeBoySchool_production
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock
